### ISSUE TITLE
csv2excel has stopped working

### ISSUE THREAD

**Issue by jerrybald** [nmolinos/csv2excel#1]
Hi Nico
My first day here, so I hope I am doing this the right way.
I have 14 csv files, all quite similar, all created with MSSQL.  
10 of them convert perfectly, the other 4 do not.
I can see no 'funny' characters in NotePadPlus.
Are there 'normal' characters which it would not like?

The runtime report is...
P:\>c:\csv2excel.exe -v -i "copy.csv"
# outputFile:
# inputFile:            copy.csv
# columnDelimiter:      ,
# lineDelimiter:        \r\n
# format:               xlsx
# outputFile (calcd):   copy.xlsx

Unhandled Exception: Microsoft.VisualBasic.FileIO.MalformedLineException: Line 1
 cannot be parsed using the current Delimiters.
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ParseDelimitedLine()
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ReadFields()
   at csv2excel.Program.writeToXLSX(String outputFile, String outputData, String
 columnDelimiter, String lineDelimiter)
   at csv2excel.Program.Main(String[] args)

It suggests (to me) that there is a problem with Line 1 of the csv.
I delete line 1 and try again but I get the same error.  
It is the exact same Line 1 which is in other files too.
I have uploaded 1 csv (as TXT) for test.

[Copy.txt](https://github.com/nmolinos/csv2excel/files/1988378/Copy.txt)

Thanks
Jerry

**Comment by nmolinos** [comment]
Hi Jerry,

The issue it is encountering is on lines 46 & 47 of your file.  It's not handling the carriage return + line feed inside the data as that matches the line delimiter being used by the file.  Your best option (if it is possible in your circumstance) is to replace "\r\n" in your data as it comes out of SQL with just "\n" so that csv2excel can differentiate between that and the true line delimiter of the data.

See this copy of "Copy.txt" where I've made the change to the data as suggested which is parsed correctly by the tool.

[Copy.txt](https://github.com/nmolinos/csv2excel/files/1989628/Copy.txt)

Thanks,

Nico
